### ISSUE TITLE
add contributers image in readme file

### ISSUE THREAD

**Issue by Beast71421** [thuongtruong1009/frontend-master#101]
![image](https://user-images.githubusercontent.com/78417225/194751075-cf67d2dd-373f-456c-8966-dc6815b9d8ae.png)
like this

**Comment by Beast71421** [comment]
@thuongtruong1009  can I have this issue, and can you please add hacktoberfest, hacktoberfest-accepted label

**Comment by thuongtruong1009** [comment]
Thanh you very much! 
I will consider to merge your PR.

**Comment by Beast71421** [comment]
can you please add hacktoberfest, hacktoberfest-accepted label
